### ISSUE TITLE
Cannot use the same name as the method

### ISSUE THREAD

**Issue by cooktheryan** [redhat-et/harpoon#43]
if you are attempting to use the same name for the config as the subdirectory to search an error will occur.

For example

```
examples/raw-config.json
examples/systemd-config.json
```

This causes harpoon to attempt to deploy those assets

**Comment by josephsawaya** [comment]
cmd/harpoon/main.go at line 80
```
t, err := tree.Tree(repo.Subdirectory)
if err != nil {
  fmt.Printf("Error searching subdirectory: %s\n", err)
}
t.Files().ForEach(func(f *object.File) error {                                                                                                                                                                                                                               
  path := directory + "/" + f.Name                                                                                                                            
  engine.EngineMethod(path, repo.Method)                                                                                                                                                                                                                                                                 
  return nil 
})
```
Currently harpoon looks at all files in the repository and if the files path contains the subdirectory string then it deploys them, that's why `examples/raw-config.json` gets deployed when the subdirectory string is `examples/raw`, I think just changing the code to move to the file tree for the subdirectory and looping through all the files there should be enough to fix it?

**Comment by cooktheryan** [comment]
@josephsawaya great call! Do you wanna take this one?
